# http://travis-ci.org/#!/graphite-project/ceres
sudo: false
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - "pypy"
before_install:
    - pip install --upgrade pip
install:
    - pip install -r test_requirements.txt
    - python setup.py install
script:
    - nosetests
    - flake8 --max-line-length=100 --ignore=E111,E114,E121 ceres.py tests/*.py bin/*
